import { NextRequest, NextResponse } from 'next/server';
import { db, accounts, userBalances, balanceTransactions } from '@/lib/db';
import { eq } from 'drizzle-orm';
import { submitForAudit } from '@/lib/account-audit-service';
import { freezeListingDeposit } from '@/lib/account-deposit-service';

/**
 * 创建账号
 * POST /api/accounts
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const {
      sellerId,
      accountId,
      title,
      description,
      screenshots,
      coinsM,
      safeboxCount,
      energyValue,
      staminaValue,
      hasSkins,
      skinTier,
      skinCount,
      hasBattlepass,
      battlepassLevel,
      customAttributes,
      tags,
      accountValue,
      recommendedRental,
      rentalRatio,
      deposit,
      totalPrice,
      rentalDays,
      rentalHours,
      rentalDescription
    } = body;

    // 验证必填字段
    if (!sellerId || !accountId || !title || !coinsM) {
      return NextResponse.json({
        success: false,
        error: '缺少必填字段'
      }, { status: 400 });
    }

    // 检查账号是否已存在
    const existingAccounts = await db
      .select()
      .from(accounts)
      .where(eq(accounts.accountId, accountId));

    if (existingAccounts.length > 0) {
      return NextResponse.json({
        success: false,
        error: '账号ID已存在'
      }, { status: 400 });
    }

    // 生成格式化的账号标题
    const generateAccountTitle = (data: any) => {
      const parts = [];

      // 哈夫币数量
      parts.push(`哈夫币${data.coinsM}M`);

      // 安全箱类型
      const safeboxType = data.safeboxCount === 4 ? '2x2' : data.safeboxCount === 6 ? '2x3' : '3x3';
      const safeboxLabel = data.safeboxCount === 9 ? '顶级安全箱' : `${data.safeboxCount}格安全箱`;
      parts.push(`${safeboxLabel}(${safeboxType})`);

      // 体力等级
      parts.push(`${data.staminaValue}体力`);

      // 负重等级
      parts.push(`${data.energyValue}负重`);

      // 段位（从tags或customAttributes中获取）
      const rank = data.tags?.find((t: string) => ['青铜', '白银', '黄金', '铂金', '钻石', '大师', '王者'].includes(t)) ||
                   data.customAttributes?.rank;
      if (rank) parts.push(rank);

      // 皮肤信息
      if (data.hasSkins && data.skinTier) {
        parts.push(data.skinTier);
        if (data.skinCount > 0) parts.push(`${data.skinCount}个皮肤`);
      }

      // 战斗通行证
      if (data.hasBattlepass) {
        parts.push(`BP${data.battlepassLevel}级`);
      }

      return parts.join('  |  ') + '  |  ';
    };

    const autoGeneratedTitle = generateAccountTitle({
      coinsM: parseFloat(coinsM.toString()),
      safeboxCount: safeboxCount || 0,
      energyValue: energyValue || 0,
      staminaValue: staminaValue || 0,
      hasSkins: hasSkins || false,
      skinTier: skinTier || null,
      skinCount: skinCount || 0,
      hasBattlepass: hasBattlepass || false,
      battlepassLevel: battlepassLevel || 0,
      customAttributes: customAttributes || {},
      tags: tags || []
    });

    // 开始事务
    const newAccount = await db.transaction(async (tx) => {
      // 1. 创建账号
      const accountData = {
        id: crypto.randomUUID(),
        sellerId,
        accountId,
        title: autoGeneratedTitle, // 使用自动生成的标题
        description: description || null,
        screenshots: screenshots || null,
        coinsM: coinsM.toString(),
        safeboxCount: safeboxCount || 0,
        energyValue: energyValue || 0,
        staminaValue: staminaValue || 0,
        hasSkins: hasSkins || false,
        skinTier: skinTier || null,
        skinCount: skinCount || 0,
        hasBattlepass: hasBattlepass || false,
        battlepassLevel: battlepassLevel || 0,
        customAttributes: customAttributes || {},
        tags: tags || [],
        accountValue: accountValue ? accountValue.toString() : null,
        recommendedRental: recommendedRental ? recommendedRental.toString() : null,
        rentalRatio: rentalRatio ? rentalRatio.toString() : null,
        deposit: deposit.toString(),
        totalPrice: totalPrice ? totalPrice.toString() : null,
        rentalDays: rentalDays ? rentalDays.toString() : null,
        rentalHours: rentalHours ? rentalHours.toString() : null,
        rentalDescription: rentalDescription || null,
        status: 'draft', // 初始状态为草稿，等待审核
        auditStatus: 'pending', // 审核状态为待审核
        viewCount: 0,
        tradeCount: 0,
        isDeleted: false
        // createdAt 和 updatedAt 使用数据库默认值 defaultNow()
      };

      const [createdAccount] = await tx.insert(accounts).values(accountData).returning();

      return createdAccount;
    });

    // 2. 冻结上架保证金
    const depositResult = await freezeListingDeposit(newAccount.id, sellerId);

    if (!depositResult.success) {
      // 如果冻结保证金失败，删除刚创建的账号
      await db.delete(accounts).where(eq(accounts.id, newAccount.id));
      return NextResponse.json({
        success: false,
        error: depositResult.message
      }, { status: 400 });
    }

    // 3. 提交审核
    const auditResult = await submitForAudit(newAccount.id);

    if (!auditResult.success) {
      return NextResponse.json({
        success: false,
        error: auditResult.message || '账号已创建，但提交审核失败',
        data: {
          account: newAccount,
          deposit: depositResult.deposit
        }
      }, { status: 500 });
    }

    return NextResponse.json({
      success: true,
      message: auditResult.message,
      data: {
        account: newAccount,
        deposit: depositResult.deposit
      }
    });
  } catch (error: any) {
    console.error('创建账号失败:', error);
    return NextResponse.json({
      success: false,
      error: error.message || '创建账号失败'
    }, { status: 500 });
  }
}

/**
 * 获取账号列表
 * GET /api/accounts
 */
export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams;
    const status = searchParams.get('status');
    const auditStatus = searchParams.get('auditStatus');
    const sellerId = searchParams.get('sellerId');

    let query = db.select().from(accounts);

    // 审核状态过滤
    // 注意：对于管理后台和卖家账号页面，需要看到所有状态的账号
    if (auditStatus) {
      query = query.where(eq(accounts.auditStatus, auditStatus)) as any;
    }

    // 状态过滤
    if (status) {
      query = query.where(eq(accounts.status, status)) as any;
    }

    // 卖家过滤
    if (sellerId) {
      query = query.where(eq(accounts.sellerId, sellerId)) as any;
    }

    // 排除已删除的账号
    query = query.where(eq(accounts.isDeleted, false)) as any;

    const accountList = await query.limit(100).orderBy(accounts.createdAt);

    return NextResponse.json({
      success: true,
      data: accountList
    });
  } catch (error: any) {
    console.error('获取账号列表失败:', error);
    return NextResponse.json({
      success: false,
      error: error.message
    }, { status: 500 });
  }
}
