import { NextRequest, NextResponse } from 'next/server';
import { and, eq } from 'drizzle-orm';
import { db, accounts } from '@/lib/db';
import { submitForAudit } from '@/lib/account-audit-service';
import { freezeListingDeposit } from '@/lib/account-deposit-service';

/**
 * 创建账号
 * POST /api/accounts
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const {
      sellerId,
      accountId,
      title,
      description,
      screenshots,
      coinsM,
      safeboxCount,
      energyValue,
      staminaValue,
      hasSkins,
      skinTier,
      skinCount,
      hasBattlepass,
      battlepassLevel,
      customAttributes,
      tags,
      accountValue,
      recommendedRental,
      rentalRatio,
      deposit,
      totalPrice,
      rentalDays,
      rentalHours,
      rentalDescription,
    } = body;

    if (!sellerId || !accountId || !title || !coinsM) {
      return NextResponse.json({
        success: false,
        error: '缺少必填字段',
      }, { status: 400 });
    }

    const existingAccounts = await db
      .select()
      .from(accounts)
      .where(eq(accounts.accountId, accountId));

    if (existingAccounts.length > 0) {
      return NextResponse.json({
        success: false,
        error: '账号ID已存在',
      }, { status: 400 });
    }

    const generateAccountTitle = (data: any) => {
      const parts = [];

      parts.push(`哈夫币${data.coinsM}M`);

      const safeboxType = data.safeboxCount === 4 ? '2x2' : data.safeboxCount === 6 ? '2x3' : '3x3';
      const safeboxLabel = data.safeboxCount === 9 ? '顶级安全箱' : `${data.safeboxCount}格安全箱`;
      parts.push(`${safeboxLabel}(${safeboxType})`);

      parts.push(`${data.staminaValue}体力`);
      parts.push(`${data.energyValue}负重`);

      const rank = data.tags?.find((t: string) => ['青铜', '白银', '黄金', '铂金', '钻石', '大师', '王者'].includes(t))
        || data.customAttributes?.rank;
      if (rank) parts.push(rank);

      if (data.hasSkins && data.skinTier) {
        parts.push(data.skinTier);
        if (data.skinCount > 0) parts.push(`${data.skinCount}个皮肤`);
      }

      if (data.hasBattlepass) {
        parts.push(`BP${data.battlepassLevel}级`);
      }

      return `${parts.join('  |  ')}  |  `;
    };

    const autoGeneratedTitle = generateAccountTitle({
      coinsM: parseFloat(coinsM.toString()),
      safeboxCount: safeboxCount || 0,
      energyValue: energyValue || 0,
      staminaValue: staminaValue || 0,
      hasSkins: hasSkins || false,
      skinTier: skinTier || null,
      skinCount: skinCount || 0,
      hasBattlepass: hasBattlepass || false,
      battlepassLevel: battlepassLevel || 0,
      customAttributes: customAttributes || {},
      tags: tags || [],
    });

    const newAccount = await db.transaction(async (tx) => {
      const accountData = {
        id: crypto.randomUUID(),
        sellerId,
        accountId,
        title: autoGeneratedTitle,
        description: description || null,
        screenshots: screenshots || null,
        coinsM: coinsM.toString(),
        safeboxCount: safeboxCount || 0,
        energyValue: energyValue || 0,
        staminaValue: staminaValue || 0,
        hasSkins: hasSkins || false,
        skinTier: skinTier || null,
        skinCount: skinCount || 0,
        hasBattlepass: hasBattlepass || false,
        battlepassLevel: battlepassLevel || 0,
        customAttributes: customAttributes || {},
        tags: tags || [],
        accountValue: accountValue ? accountValue.toString() : null,
        recommendedRental: recommendedRental ? recommendedRental.toString() : null,
        rentalRatio: rentalRatio ? rentalRatio.toString() : null,
        deposit: deposit.toString(),
        totalPrice: totalPrice ? totalPrice.toString() : null,
        rentalDays: rentalDays ? rentalDays.toString() : null,
        rentalHours: rentalHours ? rentalHours.toString() : null,
        rentalDescription: rentalDescription || null,
        status: 'draft',
        auditStatus: 'pending',
        viewCount: 0,
        tradeCount: 0,
        isDeleted: false,
      };

      const [createdAccount] = await tx.insert(accounts).values(accountData).returning();
      return createdAccount;
    });

    const depositResult = await freezeListingDeposit(newAccount.id, sellerId);

    if (!depositResult.success) {
      await db.delete(accounts).where(eq(accounts.id, newAccount.id));
      return NextResponse.json({
        success: false,
        error: depositResult.message,
      }, { status: 400 });
    }

    const auditResult = await submitForAudit(newAccount.id);

    if (!auditResult.success) {
      return NextResponse.json({
        success: false,
        error: auditResult.message || '账号已创建，但提交审核失败',
        data: {
          account: newAccount,
          deposit: depositResult.deposit,
        },
      }, { status: 500 });
    }

    return NextResponse.json({
      success: true,
      message: auditResult.message,
      data: {
        account: newAccount,
        deposit: depositResult.deposit,
      },
    });
  } catch (error: any) {
    console.error('创建账号失败:', error);
    return NextResponse.json({
      success: false,
      error: error.message || '创建账号失败',
    }, { status: 500 });
  }
}

/**
 * 获取账号列表
 * GET /api/accounts
 */
export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams;
    const status = searchParams.get('status');
    const auditStatus = searchParams.get('auditStatus');
    const sellerId = searchParams.get('sellerId');
    const limit = Math.min(Math.max(parseInt(searchParams.get('limit') || '100', 10), 1), 200);
    const conditions = [eq(accounts.isDeleted, false)];

    if (auditStatus) {
      conditions.push(eq(accounts.auditStatus, auditStatus));
    }

    if (status) {
      conditions.push(eq(accounts.status, status));
    }

    if (sellerId) {
      conditions.push(eq(accounts.sellerId, sellerId));
    }

    const accountList = await db
      .select()
      .from(accounts)
      .where(and(...conditions))
      .orderBy(accounts.createdAt)
      .limit(limit);

    return NextResponse.json({
      success: true,
      data: accountList,
    });
  } catch (error: any) {
    console.error('获取账号列表失败:', error);
    return NextResponse.json({
      success: false,
      error: error.message,
    }, { status: 500 });
  }
}
