import { NextRequest, NextResponse } from 'next/server';
import { and, eq } from 'drizzle-orm';

import { requireAdmin } from '@/lib/admin-auth';
import { submitForAudit } from '@/lib/account-audit-service';
import { freezeListingDeposit } from '@/lib/account-deposit-service';
import { db, accounts, ensureDatabaseInitialized } from '@/lib/db';
import { getServerToken } from '@/lib/server-auth';
import { verifyToken } from '@/lib/user-service';

const SKIN_RANKS = ['青铜', '白银', '黄金', '铂金', '钻石', '大师', '王者'] as const;

function formatCreateAccountError(error: unknown) {
  const errorCode = typeof (error as { code?: unknown })?.code === 'string'
    ? (error as { code: string }).code
    : '';
  const errorMessage = typeof (error as { message?: unknown })?.message === 'string'
    ? (error as { message: string }).message
    : '';

  if (errorCode === '23505') {
    return '账号ID已存在，请更换后重试';
  }

  if (errorCode === '22001') {
    return '账号信息过长，请减少皮肤或备注内容后重试';
  }

  if (
    errorCode === '42703'
    || /Failed query:/i.test(errorMessage)
    || /insert into "accounts"/i.test(errorMessage)
  ) {
    return '账号提交失败，系统数据正在同步，请稍后重试';
  }

  if (errorMessage && !/Failed query:/i.test(errorMessage)) {
    return errorMessage;
  }

  return '账号提交失败，请稍后重试';
}

function normalizeSkinTier(rawSkinTier: string | null | undefined, tags?: string[]) {
  const candidates = [
    ...(rawSkinTier ? rawSkinTier.split(',') : []),
    ...(tags || []),
  ]
    .map((item) => item.trim())
    .filter(Boolean);

  const matchedRank = candidates.find((item) =>
    SKIN_RANKS.includes(item as (typeof SKIN_RANKS)[number]),
  );

  if (matchedRank) {
    return matchedRank;
  }

  if (candidates.length > 0) {
    return '精选皮肤';
  }

  return null;
}

function generateAccountTitle(data: {
  coinsM: number;
  safeboxCount: number;
  energyValue: number;
  staminaValue: number;
  hasSkins: boolean;
  skinTier: string | null;
  skinCount: number;
  hasBattlepass: boolean;
  battlepassLevel: number;
  customAttributes?: Record<string, unknown>;
  tags?: string[];
}) {
  const parts: string[] = [];

  parts.push(`哈夫币${data.coinsM}M`);

  const safeboxType = data.safeboxCount === 4 ? '2x2' : data.safeboxCount === 6 ? '2x3' : '3x3';
  const safeboxLabel = data.safeboxCount === 9 ? '顶级安全箱' : `${data.safeboxCount}格安全箱`;
  parts.push(`${safeboxLabel}(${safeboxType})`);

  parts.push(`${data.staminaValue}体力`);
  parts.push(`${data.energyValue}负重`);

  const rank = data.tags?.find((tag) =>
    ['青铜', '白银', '黄金', '铂金', '钻石', '大师', '王者'].includes(tag),
  ) || (typeof data.customAttributes?.rank === 'string' ? data.customAttributes.rank : undefined);

  if (rank) {
    parts.push(rank);
  }

  if (data.hasSkins && data.skinTier) {
    parts.push(data.skinTier);
    if (data.skinCount > 0) {
      parts.push(`${data.skinCount}个皮肤`);
    }
  }

  if (data.hasBattlepass) {
    parts.push(`BP${data.battlepassLevel}级`);
  }

  const title = `${parts.join('  |  ')}  |  `;
  return title.length <= 100 ? title : `${title.slice(0, 97).trimEnd()}...`;
}

export async function POST(request: NextRequest) {
  try {
    await ensureDatabaseInitialized();

    const adminAuth = await requireAdmin(request);
    const token = getServerToken(request);
    const user = token ? await verifyToken(token) : null;

    if (!user && adminAuth.error) {
      return NextResponse.json({ success: false, error: '请先登录后再上架账号' }, { status: 401 });
    }

    if (user && !user.isRealNameVerified) {
      return NextResponse.json({ success: false, error: '请先完成实名认证后再上架账号' }, { status: 403 });
    }

    const body = await request.json();
    const {
      accountId,
      title,
      description,
      screenshots,
      coinsM,
      safeboxCount,
      energyValue,
      staminaValue,
      hasSkins,
      skinTier,
      skinCount,
      hasBattlepass,
      battlepassLevel,
      customAttributes,
      tags,
      accountValue,
      recommendedRental,
      rentalRatio,
      deposit,
      totalPrice,
      rentalDays,
      rentalHours,
      rentalDescription,
    } = body;

    if (!accountId || !title || !coinsM) {
      return NextResponse.json({ success: false, error: '缺少必填字段' }, { status: 400 });
    }

    const existingAccounts = await db
      .select()
      .from(accounts)
      .where(eq(accounts.accountId, accountId));

    if (existingAccounts.length > 0) {
      return NextResponse.json({ success: false, error: '账号ID已存在' }, { status: 400 });
    }

    const normalizedSkinTier = normalizeSkinTier(skinTier, tags || []);
    const autoGeneratedTitle = generateAccountTitle({
      coinsM: Number.parseFloat(coinsM.toString()),
      safeboxCount: safeboxCount || 0,
      energyValue: energyValue || 0,
      staminaValue: staminaValue || 0,
      hasSkins: hasSkins || false,
      skinTier: normalizedSkinTier,
      skinCount: skinCount || 0,
      hasBattlepass: hasBattlepass || false,
      battlepassLevel: battlepassLevel || 0,
      customAttributes: customAttributes || {},
      tags: tags || [],
    });

    const newAccount = await db.transaction(async (tx) => {
      const accountData = {
        id: crypto.randomUUID(),
        sellerId: user!.id,
        accountId,
        title: autoGeneratedTitle,
        description: description || null,
        screenshots: screenshots || null,
        coinsM: coinsM.toString(),
        safeboxCount: safeboxCount || 0,
        energyValue: energyValue || 0,
        staminaValue: staminaValue || 0,
        hasSkins: hasSkins || false,
        skinTier: normalizedSkinTier,
        skinCount: skinCount || 0,
        hasBattlepass: hasBattlepass || false,
        battlepassLevel: battlepassLevel || 0,
        customAttributes: customAttributes || {},
        tags: tags || [],
        accountValue: accountValue ? accountValue.toString() : null,
        recommendedRental: recommendedRental ? recommendedRental.toString() : null,
        rentalRatio: rentalRatio ? rentalRatio.toString() : null,
        deposit: deposit.toString(),
        totalPrice: totalPrice ? totalPrice.toString() : null,
        rentalDays: rentalDays ? rentalDays.toString() : null,
        rentalHours: rentalHours ? rentalHours.toString() : null,
        rentalDescription: rentalDescription || null,
        status: 'draft',
        auditStatus: 'pending',
        viewCount: 0,
        tradeCount: 0,
        isDeleted: false,
      };

      const [createdAccount] = await tx.insert(accounts).values(accountData).returning();
      return createdAccount;
    });

    const depositResult = await freezeListingDeposit(newAccount.id, user!.id);

    if (!depositResult.success) {
      await db.delete(accounts).where(eq(accounts.id, newAccount.id));
      return NextResponse.json({ success: false, error: depositResult.message }, { status: 400 });
    }

    const auditResult = await submitForAudit(newAccount.id);

    if (!auditResult.success) {
      return NextResponse.json({
        success: false,
        error: auditResult.message || '账号已创建，但提交审核失败',
        data: {
          account: newAccount,
          deposit: depositResult.deposit,
        },
      }, { status: 500 });
    }

    return NextResponse.json({
      success: true,
      message: auditResult.message,
      data: {
        account: newAccount,
        deposit: depositResult.deposit,
      },
    });
  } catch (error) {
    console.error('创建账号失败:', error);
    return NextResponse.json({
      success: false,
      error: formatCreateAccountError(error),
    }, { status: 500 });
  }
}

export async function GET(request: NextRequest) {
  try {
    await ensureDatabaseInitialized();

    const adminAuth = await requireAdmin(request);
    const token = getServerToken(request);
    const user = token ? await verifyToken(token) : null;
    const searchParams = request.nextUrl.searchParams;
    const status = searchParams.get('status');
    const auditStatus = searchParams.get('auditStatus');
    const sellerId = searchParams.get('sellerId');
    const limit = Math.min(Math.max(Number.parseInt(searchParams.get('limit') || '100', 10), 1), 200);
    const conditions = [eq(accounts.isDeleted, false)];

    if (auditStatus) {
      conditions.push(eq(accounts.auditStatus, auditStatus));
    }

    if (status) {
      conditions.push(eq(accounts.status, status));
    }

    if (sellerId) {
      if (adminAuth.error && user?.id !== sellerId) {
        return NextResponse.json({
          success: false,
          error: '无权查看其他卖家的账号列表',
        }, { status: 403 });
      }
      conditions.push(eq(accounts.sellerId, sellerId));
    }

    const accountList = await db
      .select()
      .from(accounts)
      .where(and(...conditions))
      .orderBy(accounts.createdAt)
      .limit(limit);

    return NextResponse.json({
      success: true,
      data: accountList,
    });
  } catch (error: any) {
    console.error('获取账号列表失败:', error);
    return NextResponse.json({
      success: false,
      error: error.message,
    }, { status: 500 });
  }
}
